chore(WalletApiHandler): change balance retrieval method to reliable source
AlphaToolsBot/alphatools pull request #52
Opened 2023-04-20 00:15 UTC by lucasvazo

web3.js installed -> yarn

2023-04-20 00:29 UTC, albertalef requested changes

2023-04-20 00:29 UTC, albertalef commented on src/renderer/src/api/WalletApiHandler.ts
> +            return balance;
Use the indentation pattern in this file (prettier or editorconfig)

2023-04-20 00:29 UTC, albertalef commented on src/renderer/src/api/WalletApiHandler.ts
> +        const weth = new web3.eth.Contract([wethAbi], wethAddress);
Separate this code in a method that return a weth contract receiving a wethAbi as a param. Put the infuraApiKey and the wethAddress in a class static constant, in future we will put this in the .env file.

2023-04-20 00:29 UTC, albertalef commented on resources/counter.txt
remove this file

2023-04-24 21:52 UTC, lucasvazo commented
> This branch need to be a fix not a chore, right?

At first I thought it was a code bug, hence the branch name, but it was an issue with the old api.
I'll keep it to fix anyway, because of the branch name

2023-04-26 18:42 UTC, albertalef requested changes

2023-04-26 18:42 UTC, albertalef commented on src/renderer/src/api/WalletApiHandler.ts
> +    }
Separate all this in other class, in future you will use a wethAbiFactory to make others requests to web3

2023-04-26 18:42 UTC, albertalef commented on src/renderer/src/api/WalletApiHandler.ts
> +                console.log(error);
```suggestion
```

2023-05-05 15:32 UTC, albertalef approved these changes
Perfect!

2023-05-05 15:33 UTC, merged